spring:
  application:
    name: payment-service



  datasource:
    url: jdbc:postgresql://localhost:5436/paymentsystemdb
    username: paymentsystem
    password: paymentsystem
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml




  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    consumer:
      group-id: payment-service-group
      client-id: payment-service-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        isolation.level: read_committed
        allow.auto.create.topics: false
    listener:
      ack-mode: manual_immediate
      concurrency: 3
      missing-topics-fatal: false
    admin:
      properties:
        request.timeout.ms: 10000

app:
  kafka:
    topics:
      order-events:
        name: order-events
      payment-events:
        name: payment-events
        partitions: 3
        replicas: 3
        configs:
          min.insync.replicas: 3
          cleanup.policy: delete
          retention.ms: 604800000
