spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5435/ordersystemdb
    username: ordersystem
    password: ordersystem
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#  разделить на prod и dev
#  в dev использовать h2
#
#
#  logging:
#    level:
#      root: INFO
#      org.springframework: INFO
#      org.hibernate: INFO
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#      org.springframework.security: DEBUG
#      org.keycloak: DEBUG


